spring:
  application:
    name: order-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/orderflow_db}
    username: ${DB_USERNAME:orderflow}
    password: ${DB_PASSWORD:orderflow_dev}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    com.sajee.order: DEBUG

server:
  port: ${SERVER_PORT:8081}